wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721395103
    t:
      1:
      - 1
      - 9
      - 55
      - 103
      2:
      - 1
      - 9
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.9.19
      5: 0.17.3
      8:
      - 1
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
seq_len:
  desc: null
  value: 3
label_choice:
  desc: null
  value: is_set
lr:
  desc: null
  value: 0.001
