#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=test_modules
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=2:00:00
#SBATCH --output=outputs/long_run.out
 
#Loading modules
module purge
module load 2023
module load Miniconda3/23.5.2-0

#Execute a Python program located in $HOME, that takes an input file and output directory as arguments.
source activate LTN
python long_run.py