wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721409747
    t:
      1:
      - 1
      - 9
      - 55
      - 103
      2:
      - 1
      - 9
      - 55
      - 103
      3:
      - 2
      - 7
      - 13
      - 23
      - 66
      4: 3.9.19
      5: 0.17.3
      8:
      - 1
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
seq_len:
  desc: null
  value: 1
label_choice:
  desc: null
  value: features
n_features:
  desc: null
  value: 2
hidden_sizes_classifier:
  desc: null
  value: []
lr:
  desc: null
  value: 0.01
