#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Miniconda3/23.5.2-0

conda create -n "LTN" python=3.9.19

pip install -r requirements_torch_cuda.txt --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt